name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  generated:
    name: Check generated files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          cache: 'npm'
      - name: Install Packages
        run: npm ci
      - name: Generate Parsers
        run: npm run generate
      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      - name: Check That Generated Files Are Unchanged
        run: git diff --exit-code origin/${{steps.extract_branch.outputs.branch}} || exit 1
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          cache: 'npm'
      - name: Install Packages
        run: npm ci
      - name: Unit Tests
        run: npm run test
