name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  generated:
    name: Generated check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          cache: 'npm'
      - name: Install Packages
        run: npm ci
      - name: Generate Parsers
        run: npm run generate
      - name: Check That Generated Files Are Unchanged
        run: git diff --name-only origin/${GITHUB_HEAD_REF}
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          cache: 'npm'
      - name: Install Packages
        run: npm ci
      - name: Unit Tests
        run: npm run test
